### ISSUE TITLE
Handling of git-remotes with names other than 'origin'

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [rgrinberg/opam-lock#4]
I've got a pinned dependency on another directory on my system, which is a checkout of a repository elsewhere on GitHub.

```
$ opam list
# Packages matching: installed
# Name                  # Installed # Synopsis
sedlex                  1.99.4      pinned to version 1.99.4 at git+file:///Users/ec/Sync/Code/Source/sedlex#add-4.02
```

My tooling, though, doesn't make use of an `origin` remote — each remote originating from a GitHub fork is instead named after the GitHub user who forked the project.

Unfortunately, that means that I get this error:

```
$ opam lock                  
opam-lock: internal error, uncaught exception:
           "/usr/local/bin/git remote get-url origin" exited with code 128 "fatal: No such remote 'origin'"
```

**Comment by rgrinberg** [comment]
You should not be using this project. https://github.com/AltGr/opam-lock offers a full featured solution.

**Comment by ELLIOTTCABLE** [comment]
Oh my lord I'm an idiot; reported on the wrong project. I'm so sorry to have wasted your time! v.v
